# Generated by Django 3.2.9 on 2021-11-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201007_0317'),
        ('jobs', '0003_auto_20201007_2201'),
    ]

    operations = [
    ]
