# Generated by Django 2.2.24 on 2022-08-28 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appearance',
        ),
    ]
