# Generated by Django 2.2.4 on 2019-11-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='track_no',
            field=models.IntegerField(default='1', max_length=2),
        ),
    ]
