# Generated by Django 2.2.4 on 2019-11-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_lyrics_track_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='track_no',
            field=models.IntegerField(default='1'),
        ),
    ]
