# Generated by Django 2.2.24 on 2022-08-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0004_delete_appearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=200)),
                ('venue_url', models.URLField()),
                ('bands', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('flyer', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
